extend schema
  @link(
    url: "https://specs.apollo.dev/federation/v2.7"
    import: ["@key", "@shareable", "@inaccessible", "@override"]
  )

type Mutation {
  ### Reviews
  "Creates reviews for both host and listing for a particular booking - must be authored by guest of past booking"
  submitHostAndLocationReviews(
    bookingId: ID! 
    hostReview: ReviewInput! 
    locationReview: ReviewInput! 
  ): SubmitHostAndLocationReviewsResponse! @override(from: "monolith")
  "Creates a review for the guest - must be authored by host of past booking"
  submitGuestReview(
    bookingId: ID! 
    guestReview: ReviewInput! 
  ): SubmitGuestReviewResponse! @override(from: "monolith")
}

type Host implements User @key(fields: "id") {
  id: ID! 
  "The overall calculated rating for the host"
  overallRating: Float @override(from: "monolith") @shareable
}

type Guest implements User @key(fields: "id") {
  id: ID!
}

type Listing @key(fields: "id") {
  id: ID!
  "The submitted reviews for this listing"
  reviews: [Review]! @override(from: "monolith")
  "The overall calculated rating for a listing"
  overallRating: Float @override(from: "monolith") @shareable
}


### Reviews

"A review consists of a numerical rating and written text. It can be written by a host or a guest."
type Review @key(fields: "id") {
  id: ID!
  "Written comment the author has written about the review target"
  text: String! @override(from: "monolith") @shareable
  "User that wrote the review"
  author: User! @override(from: "monolith") @shareable

  "The numerical rating for the review target, on a scale of 1-5, with 5 being excellent."
  rating: Float! @override(from: "monolith")
}

"ReviewInput is the bare minimum needed to submit a review, not tied to any target."
input ReviewInput {
  text: String!
  rating: Float!
}

"The response after submitting reviews for both host and location together."
type SubmitHostAndLocationReviewsResponse implements MutationResponse {
  code: Int! @override(from: "monolith")
  success: Boolean! @override(from: "monolith")
  message: String! @override(from: "monolith")
  hostReview: Review @override(from: "monolith")
  locationReview: Review @override(from: "monolith")
}

"The response after submitting reviews for a guest."
type SubmitGuestReviewResponse implements MutationResponse {
  code: Int! @override(from: "monolith")
  success: Boolean! @override(from: "monolith")
  message: String! @override(from: "monolith")
  guestReview: Review @override(from: "monolith")
}

interface MutationResponse {
  code: Int!
  success: Boolean!
  message: String!
}

interface User {
  id: ID!
}
